version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run: npm install
  deploy:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t app:latest . # Construit l'image Docker
            docker tag app:latest eliotmasset/node-js-sample:latest # Ajoute une étiquette à l'image
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push eliotmasset/node-js-sample:latest # Pousse l'image sur Docker Hub
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build